name: Test
on:
  workflow_dispatch
jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-12 ]
    name: Simple test
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set vars
        id: vars
        run: |
            if [ "$RUNNER_OS" = "macOS" ]; then
                echo "::set-output name=ENV_FILE::environment-mac.yaml"
                echo "::set-output name=PYTHON_BIN::/usr/local/miniconda/envs/ldm/bin/python"
            elif [ "$RUNNER_OS" = "Linux" ]; then
                echo "::set-output name=ENV_FILE::environment.yaml"
                echo "::set-output name=PYTHON_BIN::/usr/share/miniconda/envs/ldm/bin/python"
            fi
      - name: Set environment file
        run: |
            echo ${{ steps.vars.outputs.ENV_FILE }}
            echo ${{ steps.vars.outputs.PYTHON_BIN }}
            echo ${{ hashFiles(steps.vars.outputs.ENV_FILE) }}
